version: '3.8'

services:
  traefik:
    image: ${TRAEFIK_IMAGES}
    container_name: traefik
    restart: unless-stopped
    networks:
      - traefik-net
    command:
      - "--api.dashboard=true"
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=${ACME_MAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=${VOLUMES_LETSENCRYPT}/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ${VOLUMES_LETSENCRYPT}:/letsencrypt/

  nextcloud:
    image: ${NEXTCLOUD_IMAGE}
    container_name: nextcloud
    restart: always
    networks:
      - traefik-net
    depends_on:
      - db
    environment:
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
    volumes:
      - ${NEXTCLOUD_VOLUMES_CORE}:/var/www/html
      - ${NEXTCLOUD_VOLUMES_APPS}:/var/www/html/custom_apps
      - ${NEXTCLOUD_VOLUMES_CONFIG}:/var/www/html/config
      - ${NEXTCLOUD_VOLUMES_DATA}:/var/www/html/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`${NEXTCLOUD_HOSTNAME}`)"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.tls.certresolver=myresolver"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"

  db:
    image: ${MYSQL_IMAGE}
    container_name: nextcloud
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - ${MYSQL_VOLUMES}:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - traefik-net

  collabora:
    image: ${COLLABORA_IMAGE}
    container_name: collabora
    restart: always
    networks:
      - traefik-net
    cap_add:
      - MKNOD
    environment:
      - extra_params=--o:ssl.enable=false --o:ssl.termination=true
      - "domain=${COLLABORA_DOMAIN}"
      - DONT_GEN_SSL_CERT=YES
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.collabora.rule=Host(`${COLLABORA_HOST}`)"
      - "traefik.http.routers.collabora.entrypoints=websecure"
      - "traefik.http.routers.collabora.tls.certresolver=myresolver"
      - "traefik.http.services.collabora.loadbalancer.server.port=9980"

networks:
  traefik-net:
    driver: bridge
