global:
  checkNewVersion: true
  sendAnonymousUsage: false

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

certificatesResolvers:
  myresolver:
    acme:
      email: {{env "ACME_MAIL"}}
      storage: "{{env 'VOLUMES_LETSENCRYPT'}}/acme.json"
      httpChallenge:
        entryPoint: "web"

providers:
  docker:
    exposedByDefault: false

